{% set name = "coiled-runtime" %}
{% set version = "0.0.4" + environ.get("VERSION_SUFFIX", '') %}
{% set dask_version = environ.get("DASK_VERSION", "2022.5.0") %}
{% set distributed_version = environ.get("DISTRIBUTED_VERSION", "2022.5.0") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url:  ../

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - pip

  run:
    - python >=3.8,<3.11
    - pip
    - coiled
    - nodejs ==17.8.0
    - nb_conda_kernels ==2.3.1
    - numpy ==1.21.5
    - pandas ==1.3.5
    - dask =={{ dask_version }}
    - distributed =={{ distributed_version }}
    - fsspec ==2022.3.0
    - s3fs ==2022.3.0
    - gcsfs ==2022.3.0
    - pyarrow ==7.0.0
    - python-snappy ==0.6.0
    - jupyterlab ==3.3.2
    - dask-labextension ==5.2.0
    - lz4 ==4.0.0
    - ipywidgets ==7.7.0
    - numba ==0.55.1
    - scikit-learn ==1.0.2
    - python-graphviz ==0.19.1
    - click ==8.1.3
    - xarray ==0.20.2
    - zarr ==2.11.3
    - msgpack-python ==1.0.3
    - cloudpickle ==2.0.0
    - tornado ==6.1
    - toolz ==0.11.2
    - python-blosc ==1.10.2
    - zict ==2.2.0

test:
  imports:
    - dask
    - distributed
    - pyarrow

about:
  home: https://github.com/coiled/coiled-runtime
  summary:  "Simple and fast way to get started with Dask"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hayesgb
    - ncclementi
    - jrbourbeau
