{% set name = "coiled-runtime" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url:  ../

build:
  noarch: python
  number: 2

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - pip
    - coiled
    - nodejs ==17.8.0
    - nb_conda_kernels ==2.3.1
    - numpy ==1.21.5
    - pandas ==1.3.5
    - dask ==2022.1.0
    - distributed ==2022.1.0
    - fsspec ==2022.3.0
    - s3fs ==2022.3.0
    - gcsfs ==2022.3.0
    - pyarrow ==7.0.0
    - python-snappy ==0.6.0
    - jupyterlab ==3.3.2
    - dask-labextension ==5.2.0
    - lz4 ==4.0.0
    - ipywidgets ==7.7.0
    - numba ==0.55.1
    - scikit-learn ==1.0.2
    - python-graphviz ==0.19.1
    - click ==8.0.0
    - xarray ==0.20.2
    - zarr ==2.11.3

test:
  imports:
    - dask
    - distributed
    - pyarrow

about:
  home: https://github.com/coiled/coiled-runtime
  summary:  "Simple and fast way to get started with Dask"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hayesgb
    - ncclementi
    - jrbourbeau
