{% set name = "coiled-runtime" %}
{% set version = "0.3.0" + environ.get("VERSION_SUFFIX", '') %}
{% set dask_version = environ.get("DASK_VERSION", "2023.3.2") %}
{% set distributed_version = environ.get("DISTRIBUTED_VERSION", "2023.3.2") %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url:  ../

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - pip

  run:
    - python >=3.8,<3.11
    - pip
    - coiled >=0.5.8
    - numpy ==1.23.5
    - pandas ==1.5.3
    - dask =={{ dask_version }}
    - distributed =={{ distributed_version }}
    - fsspec ==2023.3.0
    - s3fs ==2023.3.0
    - gcsfs ==2023.3.0
    - pyarrow ==11.0.0
    - jupyterlab ==3.6.2
    - dask-labextension ==6.1.0
    - lz4 ==4.3.2
    - ipywidgets ==8.0.4  # FIXME https://github.com/dask/distributed/issues/7688
    - numba ==0.56.4
    - scikit-learn ==1.2.2
    - ipycytoscape ==1.3.3
    - click ==8.1.3
    - xarray ==2023.1.0  # Last version supporting Python 3.8
    - zarr ==2.14.2
    - msgpack-python ==1.0.5
    - cloudpickle ==2.2.1
    - tornado ==6.2
    - toolz ==0.12.0
    - zict ==2.2.0
    - xgboost ==1.7.4
    - dask-ml ==2023.3.24
    - openssl >1.1.0g
    - optuna ==3.1.0
    - scipy ==1.10.1
    - sqlalchemy ==1.4.46  # FIXME https://github.com/dask/dask/issues/9896
    - pynvml ==11.5.0
    - bokeh ==2.4.3  # FIXME https://github.com/dask/distributed/issues/7173

test:
  imports:
    - dask
    - distributed
    - pyarrow

about:
  home: https://github.com/coiled/coiled-runtime
  summary:  "Simple and fast way to get started with Dask"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hayesgb
    - ncclementi
    - jrbourbeau
