version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    groups:  # Group updates into a single PR
      g0:  # Arbitrary label; used in branch and commit messages
        update-types:
          - major
          - minor
          - patch

  - directory: /
    package-ecosystem: pip
    schedule:
      interval: weekly
    groups:  # Group updates into a single PR
      g0:  # Arbitrary label; used in branch and commit messages
        update-types:
          - major
          - minor
          - patch
    ignore:
      # https://github.com/coiled/benchmarks/issues/1221
      - dependency-name: pyspark[sql]
        versions: ["3.5.x"]
