version: 2
updates:
  - directory: ci/
    package-ecosystem: pip
    schedule:
      interval: weekly
    ignore:
      # https://github.com/coiled/benchmarks/issues/1221
      - dependency-name: pyspark
        versions: ["3.5.x"]

  - directory: AB_environments/
    package-ecosystem: pip
    schedule:
      interval: weekly
