channels:
  - conda-forge
dependencies:
########################################################
# PLEASE READ:
# When modifying this file, you must also align to match
# - AB_environments/AB_baseline.conda.yaml
# - AB_environments/AB_sample.conda.yaml
########################################################

  - python >=3.9
  - openssl >1.1.0g
  - pip-tools
  - conda
  - openjdk~=11.0  # Do not upgrade, used w/ pyspark install

########################################################
# PLEASE READ:
# When modifying this file, you must also align to match
# - AB_environments/AB_baseline.conda.yaml
# - AB_environments/AB_sample.conda.yaml
########################################################
