# This is an addition to ci/environment.yml.
# Add dependencies exclusively needed to run TPCH tests on dask competitors.
channels:
  - conda-forge
dependencies:
  # PySpark
  # See https://spark.apache.org/docs/latest/api/python/getting_started/install.html#dependencies
  - pyspark ==3.4.1 # FIXME https://github.com/coiled/benchmarks/issues/1221
  - openjdk ~=11.0  # Do not upgrade
  - grpcio ==1.61.1
  - grpcio-status ==1.60.1 # FIXME https://github.com/coiled/benchmarks/issues/1221
  - protobuf ==4.25.2

  # Other TPCH tests
  - polars ==0.20.13
