channels:
  - conda-forge
dependencies:
########################################################
# PLEASE READ:
# When modifying this file, you must also align to match
# - AB_environments/AB_baseline.conda.yaml
# - AB_environments/AB_sample.conda.yaml
########################################################

  - python >=3.9,<3.11
  - pip
  - coiled >=0.2.54
  - numpy ==1.26.2
  - pandas ==2.1.4
  - dask ==2023.12.0
  - distributed ==2023.12.0
  - dask-labextension ==7.0.0
  - dask-ml ==2023.3.24
  - fsspec ==2023.12.1
  - s3fs ==2023.12.1
  - gcsfs ==2023.12.1
  - pyarrow ==14.0.1
  - jupyterlab ==4.0.9
  - lz4 ==4.3.2
  - ipywidgets ==8.1.1
  - numba ==0.58.1
  - scikit-learn ==1.3.2
  - ipycytoscape ==1.3.3
  - click ==8.1.7
  - xarray ==2023.12.0
  - zarr ==2.16.1
  - cftime ==1.6.3
  - msgpack-python ==1.0.7
  - cloudpickle ==3.0.0
  - tornado ==6.3.3
  - toolz ==0.12.0
  - zict ==3.0.0
  - xgboost ==1.7.6
  - optuna ==3.5.0
  - scipy ==1.11.4
  - sqlalchemy ==2.0.23
  - pynvml ==11.5.0
  - bokeh ==3.3.2
  - gilknocker ==0.4.1
  - openssl >1.1.0g

########################################################
# PLEASE READ:
# When modifying this file, you must also align to match
# - AB_environments/AB_baseline.conda.yaml
# - AB_environments/AB_sample.conda.yaml
########################################################
