channels:
  - conda-forge
dependencies:
########################################################
# PLEASE READ:
# When modifying this file, you must also align to match
# - AB_environments/AB_baseline.conda.yaml
# - AB_environments/AB_sample.conda.yaml
########################################################

  - python >=3.10
  - pip
  - coiled >=0.2.54
  - numpy ==1.26.4
  - pandas ==2.2.2
  - dask ==2024-07.1
  - distributed ==2024-07.1
  - dask-expr ==1.1.9
  - dask-labextension ==7.0.0
  - dask-ml ==2024.4.4
  - fsspec ==2024.6.1
  - s3fs ==2024.6.1
  - gcsfs ==2024.6.1
  - pyarrow ==15.0.0
  - jupyterlab ==4.2.4
  - lz4 ==4.3.3
  - ipywidgets ==8.1.3
  - numba ==0.60.0
  - scikit-learn ==1.5.1
  - ipycytoscape ==1.3.3
  - click ==8.1.7
  - xarray ==2024.07.0
  - flox ==0.9.9
  - zarr ==2.18.2
  - cftime ==1.6.4
  - msgpack-python
  - cloudpickle ==3.0.0
  - tornado ==6.4.1
  - toolz ==0.12.1
  - zict ==3.0.0
  - xgboost ==2.1.1
  - optuna ==3.6.1
  - optuna-integration ==3.6.0
  - scipy ==1.14.0
  - sqlalchemy ==2.0.31
  - pynvml ==11.5.3
  - bokeh ==3.5.1
  - gilknocker ==0.4.1
  - openssl >1.1.0g
  - rioxarray ==0.17.0
  - h5netcdf ==1.3.0
  - xesmf ==0.8.7
  - bottleneck ==1.4.1

########################################################
# PLEASE READ:
# When modifying this file, you must also align to match
# - AB_environments/AB_baseline.conda.yaml
# - AB_environments/AB_sample.conda.yaml
########################################################
