channels:
  - conda-forge
dependencies:
  - jinja2
  - packaging
  - pytest
  - pytest-xdist
  - pyyaml
  - sqlalchemy
  - alembic
  # Temporary workaround for `filelock=3.11.0` causing package sync to deadlock
  - filelock=3.10.7
  - cftime
