# This is an addition to ci/environment.yml.
# Add dependencies exclusively needed to run TPCH tests on dask competitors.
channels:
  - conda-forge
dependencies:
  # PySpark
  # See https://spark.apache.org/docs/latest/api/python/getting_started/install.html#dependencies
  - pyspark ==3.4.1 # FIXME https://github.com/coiled/benchmarks/issues/1221
  - openjdk ~=11.0  # Do not upgrade
  - grpcio ==1.59.3
  - grpcio-status ==1.57.0 # FIXME https://github.com/coiled/benchmarks/issues/1221
  - protobuf ==4.24.4

  # Other TPCH tests
  - python-duckdb ==0.9.2
  - polars ==0.19.19
