# This is an addition to ci/environment.yml.
# Add dask-snowflake and downgrade some pinned dependencies.
channels:
  - conda-forge
dependencies:
  - pip
  - snowflake-connector-python ==3.12.2
  - snowflake-sqlalchemy ==1.6.1
  - pip:
    - git+https://github.com/coiled/dask-snowflake
