channels:
  - conda-forge
dependencies:
  - jinja2
  - packaging
  - pytest
  - pytest-xdist
  - python
  - pyyaml
  - sqlalchemy ==1.4.46  # FIXME https://github.com/dask/dask/issues/9896
  - alembic
  - filelock
  - conda
