# This is an addition to ci/environment.yml.
# Add dependencies exclusively needed to run geospatial tests.
channels:
  - conda-forge
dependencies:
  - memray ==1.13.4
  - dask ==2024.9.0
  - dask-expr ==1.1.14
  - distributed ==2024.9.0
  - xarray ==2024.9.0
