channels:
  - conda-forge
dependencies:
  - python >=3.9
  - pip
  - coiled >=0.2.54
  - numpy ==1.23.5
  - pandas ==2.0.1
  - dask ==2023.5.1
  - distributed ==2023.5.1
  - fsspec ==2023.5.0
  - s3fs ==2023.5.0
  - gcsfs ==2023.5.0
  - pyarrow ==11.0.0
  - jupyterlab ==3.6.2
  - dask-labextension ==6.1.0
  - lz4 ==4.3.2
  - ipywidgets ==8.0.4  # FIXME https://github.com/dask/distributed/issues/7688
  - numba ==0.57.0
  - scikit-learn ==1.2.2
  - ipycytoscape ==1.3.3
  - click ==8.1.3
  - xarray ==2023.4.2
  - zarr ==2.14.2
  - cftime ==1.6.2
  - msgpack-python ==1.0.5
  - cloudpickle ==2.2.1
  - tornado ==6.2
  - toolz ==0.12.0
  - zict ==3.0.0
  - xgboost ==1.7.4
  - dask-ml ==2023.3.24
  - optuna ==3.1.0
  - scipy ==1.10.1
  - sqlalchemy ==2.0.12
  - pynvml ==11.5.0
  - bokeh ==3.1.0
  - gilknocker ==0.4.1
  - openssl >1.1.0g
  - pyopenssl ==23.2.0
  - cryptography ==41.0.0
