name: Geospatial Workflow
on:
  workflow_dispatch:
    inputs:
      scale:
        description: "Scale"
        required: true
        default: "large"
        type: choice
        options:
          - "small"
          - "large"

defaults:
  # Required shell entrypoint to have properly activated conda environments
  run:
    shell: bash -l {0}

jobs:
  geospatial:
    name: Geospatial
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-variant: Mambaforge
        use-mamba: true
        condarc-file: ci/condarc
        python-version: "3.9"
        environment-file: ci/environment.yml

    - name: Upgrade dask to git tip
      run: mamba env update --file ci/environment-git-tip.yml

    - name: Add test dependencies
      run: mamba env update --file ci/environment-test.yml

    - name: Dump environment
      run: |
        # For debugging
        echo -e "--\n--Conda Environment (re-create this with \`conda env create --name <name> -f <output_file>\`)\n--"
        mamba env export | grep -E -v '^prefix:.*$'

    - name: Google auth
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

    - name: Run Geospatial workflow
      env:
        DASK_COILED__TOKEN: ${{ secrets.COILED_BENCHMARK_BOT_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.RUNTIME_CI_BOT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.RUNTIME_CI_BOT_AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2 # this is needed for boto for some reason
        COILED_RUNTIME_VERSION: ${{ matrix.runtime-version }}
        DB_NAME: geospatial_${{ inputs.scale }}.db
        CLUSTER_DUMP: always
      run: |
        pytest \
            --benchmark \
            --scale ${{ inputs.scale }} \
            tests/geospatial \
            -n 4 --dist loadscope

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: geospatial-benchmark
        path: |
          geospatial_${{ inputs.scale }}.db
          mamba_env_export.yml
