name: h2o groupby benchmark

on:
  workflow_dispatch:
  push:

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: conda-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        software-env: ["coiled_dist-py38", "coiled_dist-py39"]
        include:
          - software-env: "coiled_dist-py38"
            env-file: h2o_benchmark/envs/coiled_dist-py38.yml
            
          - software-env: "coiled_dist-py39"
            env-file: h2o_benchmark/envs/coiled_dist-py39.yml

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Build local ${{ matrix.software-env }} conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: ${{ matrix.env-file }}

      - name: List conda packages
        shell: bash -l {0}
        run: conda list

      - name: Build ${{ matrix.software-env }} software environment
        env:
          DASK_COILED__TOKEN: ${{ secrets.COILED_BENCHMARK_BOT_TOKEN }}
        shell: bash -l {0}
        run: coiled env create --name dask-engineering/${{ matrix.software-env }} --conda ${{ matrix.env-file }}

      - name: Run groupby benchmark 
        env:
          DASK_COILED__TOKEN: ${{ secrets.COILED_BENCHMARK_BOT_TOKEN }}
          SOFTWARE_ENV: dask-engineering/${{ matrix.software-env }}
        shell: bash -l {0}
        run: python h2o_benchmark/groupby_h2o.py