name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0

  recipe:
    runs-on: ubuntu-latest
    # Required shell entrypoint to have properly activated conda environments
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: "3.9"

      - name: Install conda-smithy
        run: mamba install conda-smithy

      - name: Lint recipe
        run: conda-smithy recipe-lint recipe