name: pip installation
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

concurrency:
  # Include `github.event_name` to avoid pushes to `main` and
  # scheduled jobs canceling one another
  group: pip-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  # Required shell entrypoint to have properly activated conda environments
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install coiled-runtime with pip
        run: python -m pip install -e .

      - name: Run tests
        run: python -m pytest --run-latest tests/runtime/test_build.py