name: pip installation
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

concurrency:
  # Include `github.event_name` to avoid pushes to `main` and
  # scheduled jobs canceling one another
  group: pip-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  # Required shell entrypoint to have properly activated conda environments
  run:
    shell: bash -l {0}

jobs:
  build:
    if: ${{ false }} # skip CI during holidays revert on Jan 3rd
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          python-version: "3.10"
          environment-file: ci/environment.yml

      - name: Install coiled-runtime with pip
        run: python -m pip install -e .

      - name: Run tests
        run: python -m pytest --run-latest tests/runtime/test_build.py