name: Build docker image and deploy

on:
  push:
    branches: "main"
    paths:
      - environments/**
  pull_request: "main"   # only to test while developing    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [runtime_0-0-3_py39]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build and push ${{ matrix.image }} image
      uses: docker/build-push-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: coiled/${{ matrix.image }}
        tag_with_ref: true
        tag_with_sha: true