name: Build docker image and deploy

on:
  push:
    branches: main
    paths:
      - environments/**
  pull_request: # only to test while developing

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [runtime_0-0-3_py39]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push ${{ matrix.image }} image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: coiledci/${{ matrix.image }}:latest
